# Generated by Django 3.1.3 on 2020-11-04 15:20

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('number_of_floors', models.IntegerField(default=1)),
                ('juristic_persons_number', models.TextField(max_length=25)),
                ('common_fee_account', models.TextField(max_length=25)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('elevator', 'Elevator'), ('parking_lot', 'Parking Lot'), ('cctv', 'CCTV'), ('security', 'Security'), ('wifi', 'WiFi'), ('swimming_pool', 'Swimming Pool'), ('sauna', 'Sauna'), ('garden', 'Garden'), ('playground', 'Playground'), ('gym', 'Gym'), ('shop', 'Shop'), ('restaurant', 'Restaurant')], default=None, max_length=97)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('line_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('still_on_contract', models.BooleanField(default=False)),
                ('price_for_rent', models.FloatField(default=0)),
                ('price_for_sell', models.FloatField(default=0)),
                ('floor_number', models.CharField(default='1', max_length=10)),
                ('number_of_bedroom', models.IntegerField(default=1)),
                ('number_of_bathroom', models.IntegerField(default=1)),
                ('area', models.FloatField(default=0)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.condo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estate.owner')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estate/images/room/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.room')),
            ],
        ),
        migrations.CreateModel(
            name='CondoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estate/images/condo/')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.condo')),
            ],
        ),
    ]
