# Generated by Django 3.1.2 on 2020-11-01 03:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('elevator', 'Elevator'), ('parking_lot', 'Parking Lot'), ('cctv', 'CCTV'), ('security', 'Security'), ('wifi', 'WiFi'), ('swimming_pool', 'Swimming Pool'), ('sauna', 'Sauna'), ('garden', 'Garden'), ('playground', 'Playground'), ('gym', 'Gym'), ('shop', 'Shop'), ('restaurant', 'Restaurant')], default=None, max_length=97),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
