# Generated by Django 3.1 on 2020-10-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20201027_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number_of_floor',
            new_name='floor_number',
        ),
    ]
