# Generated by Django 3.1 on 2020-10-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_auto_20201027_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condo',
            name='cctv',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='parking_lot',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='playground',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='restaurant_on_premise',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='sauna',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='security',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='shop_on_premise',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='swimming_pool',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='wifi',
        ),
    ]
